config/routes.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2016, Sebastian Staudt

Rails.application.routes.draw do

  scope format: false, defaults: { format: :html } do
    resources :repositories, path: 'repos', only: [],
              constraints: { repository_id: /[0-9A-Za-z_-]+?\/[0-9A-Za-z_-]+/ } do
      resources :formulae, only: :browse, path: 'browse' do
        get ':letter(/:page)', action: :browse, on: :collection,
            as: :letter,
            constraints: { letter: /[A-Za-z]/, page: /\d+/ }
      end

      resources :formulae, only: :browse, path: 'search' do
        get '(:search(/:page))', action: :search, on: :collection,
            as: :search,
            constraints: { page: /\d+/, search: /[^\/]+/ }
      end

      resources :formula, controller: :formulae, only: :show,
                constraints: { id: /[^\/]+/ } do
        get '/version', controller: :api, action: :version, as: :version,
            constraints: { format: :json }, defaults: { format: :json },
            format: nil
      end

      scope format: true, :constraints => { :format => 'atom' } do
        get '/feed' => 'formulae#feed', as: :feed
      end
    end

    resources :formulae, only: :browse, path: 'browse' do
      get ':letter(/:page)', action: :browse, on: :collection,
          as: :letter,
          constraints: { letter: /[A-Za-z]/, page: /\d+/ }
    end

    resources :formulae, only: :browse, path: 'search' do
      get '(:search(/:page))', action: :search, on: :collection,
          as: :search,
          constraints: { page: /\d+/, search: /[^\/]+/ }
    end

    resources :formula, controller: :formulae, only: :show,
              constraints: { id: /[^\/]+/ } do
      get '/version', controller: :api, action: :version, as: :version,
          constraints: { format: :json }, defaults: { format: :json },
          format: nil
    end
  end

  scope format: true do
    scope constraints: { format: :atom } do
      get '/feed', to: 'formulae#feed', as: :feed
    end

    scope constraints: { format: :xml } do
      get '/sitemap', to: 'application#sitemap', as: :sitemap
    end
  end

  root to: 'application#index'
  get '/status', to: 'application#status'

  get '*url', to: 'application#not_found', format: false

  delete '/', to: 'application#forbidden', format: false
  delete '*url', to: 'application#forbidden', format: false
  post '/', to: 'application#forbidden', format: false
  post '*url', to: 'application#forbidden', format: false
  put '/', to: 'application#forbidden', format: false
  put '*url', to: 'application#forbidden', format: false
  match '/', via: :options, to: 'application#forbidden', format: false
  match '*url', via: :options, to: 'application#forbidden', format: false

end

app/controllers/formulae_controller.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2017, Sebastian Staudt

require 'text'

class FormulaeController < ApplicationController

  before_action :ensure_html, except: :feed
  before_action :select_repository

  def browse
    letter = params[:letter]
    @title = "Browse formulae – #{letter.upcase}"
    @title << " – #{helpers.name}" unless all?

    @formulae = formulae.letter(letter)
                        .where(removed: false).order_by(%i[name asc])
                        .page(params[:page]).per 30

    fresh_when etag: etag, public: true
  end

  def feed
    revisions = all? ? Revision : @repository.revisions
    @revisions = revisions.without_bot
                          .includes(:author, :added_formulae, :updated_formulae, :removed_formulae)
                          .order_by(%i[date desc]).limit 50

    respond_to do |format|
      format.atom
    end

    fresh_when etag: etag, public: true
  end

  def search
    return not_found if params[:search].nil?

    term = params[:search].force_encoding('UTF-8').delete "\u0000"
    @title = "Search for: #{term}"
    @title << " in #{helpers.name}" unless all?
    search_term = /#{Regexp.escape term}/i
    @formulae = formulae.and removed: false, :$or =>
      [
        { aliases: search_term },
        { description: search_term },
        { name: search_term }
      ]

    if @formulae.size == 1 && term == @formulae.first.name
      redirect_to @formulae.first
      return
    end

    @formulae = @formulae.sort_by! do |formula|
      Text::Levenshtein.distance(formula.name[0..term.size - 1], term) * 10 +
        Text::Levenshtein.distance(formula.name, term)
    end
    @formulae = Kaminari.paginate_array(@formulae).page(params[:page]).per 30

    respond_to do |format|
      format.html { render 'formulae/browse' }
    end

    fresh_when etag: etag, public: true
  end

  def show
    @formulae = formulae.includes(:deps, :revdeps).where(name: params[:id]).to_a
    if @formulae.empty?
      formula = formulae.all_in(aliases: [params[:id]]).first
      unless formula.nil?
        redirect_to formula
        return
      end
      raise Mongoid::Errors::DocumentNotFound.new(Formula, [], params[:id])
    elsif @formulae.size > 1
      @formulae = Kaminari.paginate_array @formulae, limit: @formulae.size, offset: 0

      respond_to do |format|
        format.html { render 'formulae/browse' }
      end

      return
    end
    @formula = @formulae.first
    @title = @formula.name.dup
    @title << " – #{helpers.name}" unless all?
    @revisions = @formula.revisions.limit(5).without_bot.includes(:author)
                         .order_by(%i[date desc]).to_a

    fresh_when etag: etag, public: true
  end

  protected

  def all?
    @repository.nil?
  end
  helper_method :all?

  def etag
    if all? && Revision.last
      Revision.last.sha
    elsif @repository
      @repository.sha
    end
  end

  def formulae
    if all?
      Formula
    elsif @repository
      @repository.formulae
    end
  end

  def select_repository
    repository_id = params[:repository_id]
    return if repository_id.nil?

    @repository = Repository.where(_id: /^#{repository_id}$/i)
                            .only(:_id, :letters, :name, :sha, :updated_at).first
    if @repository.nil?
      raise Mongoid::Errors::DocumentNotFound.new Repository, [], repository_id
    end

    if @repository.name != repository_id
      redirect_to request.url.sub "/repos/#{repository_id}", "/repos/#{@repository.name}"
    end
  end

end

app/helpers/formulae_helper.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2017, Sebastian Staudt

require 'digest'

module FormulaeHelper

  def code_link(formula, revision)
    link_to 'Formula code', "https://github.com/#{formula.repository.name}/blob/#{revision.sha}/#{formula.path}", target: :_blank
  end

  def formula_diff_link(formula, rev)
    diff_md5 = Digest::MD5.hexdigest formula.path
    link_to '', "https://github.com/#{formula.repository.name}/commit/#{rev.sha}#diff-#{diff_md5}", target: :_blank
  end

  def feed_link
    feed_link = '/feed.atom'
    feed_link = "/repos/#{@repository.name}" + feed_link unless all?
    feed_link
  end

  def history_link(formula)
    link_to 'Complete formula history at GitHub', "https://github.com/#{formula.repository.name}/commits/HEAD/#{formula.path}", target: :_blank
  end

  def letters
    if all?
      Repository.all.map(&:letters).flatten.uniq.sort
    else
      @repository.letters
    end
  end

  def name
    all? ? nil : @repository.name
  end

end

app/views/formulae/_formula.html.erb
<tr class="formula <%= cycle 'even', 'odd' %><%= ' removed' if formula.removed? %>">
  <td><%= formula_link formula %></td>
  <td><span class="spec-<%= formula.best_spec %>"></td>
  <td>
    <strong class="version">
      <%= formula.version %><%= "_#{formula.revision}" if formula.revision > 0 %>
    </strong>
  </td>
  <td class="desc"><%= formula.description %></td>
</tr>

app/views/formulae/_search.html.erb
<form action="<%= search_formulae_path %>" id="search-form">
  <%= "🔎" if local_assigns[:with_icon] %>
  <input id="search" name="search" type="text" placeholder="<%= params[:search] || 'Search for formulae…'.html_safe %>" />
</form>

app/views/formulae/browse.html.erb
<h1>Package listing</h1>
<p class="listing-header">
  <% if all? %>
    This is a listing of all packages available via the Homebrew package manager
    for macOS.
  <% else %>
    This is a listing of all Homebrew packages available in the tap repository
    <%= link_to name, "https://github.com/#{name}" %>.
  <% end %>
</p>

<%= link_to icon('rss-square'), feed_link, class: 'feed-link', title: t('.feed_title', name: name) %>

<%= render partial: 'search', locals: { with_icon: true } %>

<ul id="letters">
  <% ('a'..'z').each do |letter| %>
    <li>
      <% if letters.include? letter
        letter_url = all? ? letter_formulae_path(letter) : letter_repository_formulae_path(name, letter)
        letter_class = 'current' if letter == (params[:letter] || '').downcase %>
        <%= link_to_unless_current letter.upcase, letter_url, class: letter_class do %>
          <span class="current"><%= letter.upcase %></span>
        <% end %>
      <% else %>
        <%= letter.upcase %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if @formulae.total_count == 0 %>
  <div class="border-bottom"></div>
  <div class="border-top"></div>
  <div class="error">Sorry, no formulae are matching your search.</div>
<% else
  page_params = { id: nil }
  if params.key?(:search) && !params[:search].empty?
    page_params[:use_route] = :search_formulae
  end
  pagination = paginate @formulae, params: page_params %>

  <% content_for :kaminari do %>
    <%= rel_next_prev_link_tags @formulae %>
  <% end %>

  <%= pagination %>

  <div class="border-bottom"></div>
  <div class="border-top"></div>

  <div class="listing browse">
    <table>
      <%= render partial: 'formula', collection: @formulae %>
    </table>
  </div>

  <%= pagination %>
<% end %>

app/views/formulae/show.html.erb
<div class="show">
  <h1><%= @formula.name %></h1>
  <% unless all? %>
    <div class="subtitle">in <%= link_to name, letter_repository_formulae_path(@repository, @repository.first_letter), class: 'repo' %></div>
  <% end %>

  <div id="basic">
    <% unless @formula.description.nil? %>
      <div id="description"><%= @formula.description %></div>
    <% end %>

    <% unless @formula.homepage.nil? %>
      <span><em><%= link_to @formula.homepage, @formula.homepage %></em></span>
    <% end %>

    <% unless (@formula.aliases || []).empty? %>
      Also known as: <strong><%= safe_join @formula.aliases, '</strong>, <strong>'.html_safe %></strong><br>
    <% end %>

    <% if @formula.keg_only? %>
      <strong>This formula is <abbr title="A keg-only formula won't be symlinked automatically.">keg-only</abbr>.</strong><br>
    <% end %>

    <h2<% if @formula.removed? %>class="removed"<% end %>>
      <% if @formula.removed? %>
        Formula was removed<br>
      <% end %>
      <%= t ".versions#{'.removed' if @formula.removed? }", count: @formula.versions.size %>
      <table class="versions">
        <% unless @formula.stable_version.nil? %>
          <tr>
            <td><span class="spec-stable"></td>
            <td><strong class="version"><%= @formula.stable_version %></strong></td>
          </tr>
        <% end %>
        <% unless @formula.devel_version.nil? %>
          <tr>
            <td><span class="spec-devel"></td>
            <td><strong class="version"><%= @formula.devel_version %></strong></td>
          </tr>
        <% end %>
        <% unless @formula.head_version.nil? %>
          <tr>
            <td><span class="spec-head"></td>
            <td><strong class="version"><%= @formula.head_version %></strong></td>
          </tr>
        <% end %>
      </table>
    </h2>
    <% if @formula.revision > 0 %>
      <h2>Revision: <%= @formula.revision %></h2>
    <% end %>
  </div>

  <% deps = @formula.deps.reject { |formula| formula.removed? } %>
  <% unless deps.empty? %>
    <div id="deps">
      <%= t '.deps_html', name: @formula.name, count: @formula.deps.size %>

      <table>
        <%= render partial: 'formula', collection: deps %>
      </table>
    </div>
  <% end %>

  <% reset_cycle %>

  <% revdeps = @formula.revdeps.reject { |formula| formula.removed? } %>
  <% unless revdeps.empty? %>
    <div id="revdeps">
      <h2>Reverse dependencies</h2>
      <%= t '.revdeps_html', name: @formula.name, count: @formula.revdeps.size %>
      <table>
        <%= render partial: 'formula', collection: revdeps %>
      </table>
    </div>
  <% end %>

  <% unless @revisions.empty? %>
  <div id="history">
    <h2>Recent formula history</h2>
    <table>
    <% @revisions.each_with_index do |rev, i| %>
      <tr<% if i == 0 %> class="current"<% end %>>
        <td class="author">
          <%= formula_diff_link @formula, rev %>
          <%= rev.author.name %></td>
        <td class="subject">
          <%= formula_diff_link @formula, rev %>
          <%= rev.subject %>
        </td>
        <td class="date">
          <%= formula_diff_link @formula, rev %>
          <%= timestamp rev.date %>
        </td>
      </tr>
    <% end %>
    <tr class="history-link">
      <td colspan="3">
        <%= history_link @formula %>
      </td>
    </tr>
    </table>
  </div>

  <br>

  <%= code_link @formula, @revisions.first %> at GitHub
  <% end %>
</div>