config/routes.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2016, Sebastian Staudt

Rails.application.routes.draw do

  scope format: false, defaults: { format: :html } do
    resources :repositories, path: 'repos', only: [],
              constraints: { repository_id: /[0-9A-Za-z_-]+?\/[0-9A-Za-z_-]+/ } do
      resources :formulae, only: :browse, path: 'browse' do
        get ':letter(/:page)', action: :browse, on: :collection,
            as: :letter,
            constraints: { letter: /[A-Za-z]/, page: /\d+/ }
      end

      resources :formulae, only: :browse, path: 'search' do
        get '(:search(/:page))', action: :search, on: :collection,
            as: :search,
            constraints: { page: /\d+/, search: /[^\/]+/ }
      end

      resources :formula, controller: :formulae, only: :show,
                constraints: { id: /[^\/]+/ } do
        get '/version', controller: :api, action: :version, as: :version,
            constraints: { format: :json }, defaults: { format: :json },
            format: nil
      end

      scope format: true, :constraints => { :format => 'atom' } do
        get '/feed' => 'formulae#feed', as: :feed
      end
    end

    resources :formulae, only: :browse, path: 'browse' do
      get ':letter(/:page)', action: :browse, on: :collection,
          as: :letter,
          constraints: { letter: /[A-Za-z]/, page: /\d+/ }
    end

    resources :formulae, only: :browse, path: 'search' do
      get '(:search(/:page))', action: :search, on: :collection,
          as: :search,
          constraints: { page: /\d+/, search: /[^\/]+/ }
    end

    resources :formula, controller: :formulae, only: :show,
              constraints: { id: /[^\/]+/ } do
      get '/version', controller: :api, action: :version, as: :version,
          constraints: { format: :json }, defaults: { format: :json },
          format: nil
    end
  end

  scope format: true do
    scope constraints: { format: :atom } do
      get '/feed', to: 'formulae#feed', as: :feed
    end

    scope constraints: { format: :xml } do
      get '/sitemap', to: 'application#sitemap', as: :sitemap
    end
  end

  root to: 'application#index'
  get '/status', to: 'application#status'

  get '*url', to: 'application#not_found', format: false

  delete '/', to: 'application#forbidden', format: false
  delete '*url', to: 'application#forbidden', format: false
  post '/', to: 'application#forbidden', format: false
  post '*url', to: 'application#forbidden', format: false
  put '/', to: 'application#forbidden', format: false
  put '*url', to: 'application#forbidden', format: false
  match '/', via: :options, to: 'application#forbidden', format: false
  match '*url', via: :options, to: 'application#forbidden', format: false

end

app/controllers/application_controller.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2017, Sebastian Staudt

class ApplicationController < ActionController::Base

  class RepositoryUnavailable < StandardError; end

  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, only: :forbidden

  rescue_from Mongoid::Errors::DocumentNotFound, with: :not_found
  rescue_from RepositoryUnavailable do
    error_page :service_unavailable
  end

  before_action :ensure_html

  def index
    main_page

    respond_to do |format|
      format.html { render 'application/index' }
      format.any { render nothing: true, status: :not_found }
    end

    fresh_when etag: Repository.core.sha, public: true
  end

  def status
    respond_to do |format|
      format.html { render 'application/status' }
      format.any { render nothing: true, status: :not_found }
    end

    fresh_when etag: Repository.core.sha, public: true
  end

  def error_page(status = :internal_server_error)
    view = 'application/%d'.format(Rack::Utils::SYMBOL_TO_STATUS_CODE[status])

    respond_to do |format|
      format.html { render view, status: status }
      format.any { render nothing: true, status: status }
    end

    headers.delete 'ETag'
    expires_in 5.minutes
  end

  def forbidden
    respond_to do |format|
      format.any { render nothing: true, status: :forbidden }
    end
  end

  def not_found
    flash.now[:error] = 'The page you requested does not exist.'
    main_page

    respond_to do |format|
      format.html { render 'application/index', status: :not_found }
      format.any { head :not_found }
    end

    headers.delete 'ETag'
    expires_in 5.minutes
  end

  def sitemap
    @repository = Repository.only(:_id, :sha, :updated_at).core

    respond_to do |format|
      format.xml
    end

    fresh_when etag: @repository.sha, public: true
  end

  protected

  def ensure_html
    head 406 unless request.format.html? || request.request_method == 'HEAD'
  end

  private

  def main_page
    @taps = Repository.only(%i[_id date letters name sha updated_at])
                      .current_taps.order_by(%i[name asc])
                      .sort_by { |r| r.core? ? 0 : 1 }

    top5 = Formula.limit(5).order_by(%i[date desc])
                  .only %i[_id name repository_id]
    linked_formulae = top5.where(removed: false)
                          .only %i[devel_version head_version stable_version]

    @added = linked_formulae.with_size revision_ids: 1
    @updated = linked_formulae.not.with_size revision_ids: 1
    @removed = top5.where removed: true
  end

end

app/helpers/application_helper.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2017, Sebastian Staudt

module ApplicationHelper

  def formula_link(formula, options = {})
    options = { class: 'formula' }.merge options
    url_options = formula.dupe? ? [formula.repository, formula] : formula
    link_to formula.name, url_for(url_options), options
  end

  def timestamp(time)
    options = {
      class: 'timeago',
      datetime: time.getutc.iso8601
    }
    content_tag :time, l(time, format: :long), options
  end

  def title
    title = 'Homebrew Formulae'
    title = "#{@title} – #{title}" unless @title.nil?
    title
  end

end

app/views/application/500.html.erb
<h1>Someone spilled our beer!</h1>
<p>Something went horribly wrong while you tried to access our pages.
But fear not, we have been notified of the problem.</p>
<p>Please try again in a few seconds. If the problem persists, feel
free to contact
<a href="https://twitter.com/braumeister_org">@braumeister_org</a> on
Twitter.</p>

app/views/application/503.html.erb
<h1>Currently unavailable</h1>
The repository is currently unavailable – probably because its content is
being reimported at the moment.

app/views/application/_recent.html.erb
<tr class="formula <%= cycle 'even', 'odd' %>">
  <td><%= formula_link formula %></td>
  <td><span class="spec-<%= formula.best_spec %>"></td>
  <td><strong class="version"><%= formula.version %></strong></td>
</tr>

app/views/application/index.html.erb
<div id="home" class="border-bottom">
  <strong>formulae.brew.sh</strong> is an online package browser for
  <%= link_to 'Homebrew', 'https://brew.sh' %> – the macOS package manager.<br>
  For more information on how to install and use Homebrew see <%= link_to 'our homepage', 'https://brew.sh' %>.

  <%= link_to 'Browse all formulae', letter_formulae_path('a'), class: 'center' %>

  <h2>🔎</h2>
  <%= render partial: 'formulae/search' %>
</div>

<div class="border-top" ></div>

<div class="recently-added">
  <h3>🆕 Recently added formulae</h3>
  <div class="listing">
    <table>
      <% @added.each do |formula| %>
        <%= render partial: 'recent', locals: { formula: formula } %>
      <% end %>
    </table>
  </div>
</div>

<% reset_cycle %>

<div class="recently-updated">
  <h3>📝 Recently updated formulae</h3>
  <div class="listing">
    <table>
      <% @updated.each do |formula| %>
        <%= render partial: 'recent', locals: { formula: formula } %>
      <% end %>
    </table>
  </div>
</div>

<div class="recently-removed">
  <h3>🚫 Recently removed formulae</h3>
  <%= @removed.map { |f| formula_link f }.join(', ').html_safe %>
</div>

<div class="border-bottom" ></div>

<div id="taps" class="border-top">
  <h2>🚰 Browse specific taps</h2>
  <div class="listing">
  <% @taps.each do |repo| %>
    <div class="repo">
      <% if letter = repo.letters.first %>
        <%= link_to repo.short_name, letter_repository_formulae_path(repo, letter) %>
      <% else %>
        <%= repo.short_name %>
      <% end %></div>
  <% end %>
  </div>
</div>

app/views/application/status.html.erb
<div id="status" class="border-bottom">
  <strong>formulae.brew.sh</strong> is an online package browser for
  <%= link_to 'Homebrew', 'https://brew.sh' %> – the macOS package manager.<br>
  For more information on how to install and use Homebrew see <%= link_to 'our homepage', 'https://brew.sh' %>.

  <%= link_to 'Browse all formulae', letter_formulae_path('a'), class: 'center' %>

  <h2>🔎</h2>
  <%= render partial: 'formulae/search' %>
</div>

<div class="border-top"></div>

<h1>Status</h1>

<div id="timestamps">
  The repository has been updated <%= timestamp Repository.core.updated_at %>.<br>
  The last change happened <%= timestamp Repository.core.date %>.<br>
  Current Git commit SHA: <%= link_to Repository.core.sha, "https://github.com/#{Repository.core.name}/tree/#{Repository.core.sha}" %>
</div>