config/routes.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2016, Sebastian Staudt

Rails.application.routes.draw do

  scope format: false, defaults: { format: :html } do
    resources :repositories, path: 'repos', only: [],
              constraints: { repository_id: /[0-9A-Za-z_-]+?\/[0-9A-Za-z_-]+/ } do
      resources :formulae, only: :browse, path: 'browse' do
        get ':letter(/:page)', action: :browse, on: :collection,
            as: :letter,
            constraints: { letter: /[A-Za-z]/, page: /\d+/ }
      end

      resources :formulae, only: :browse, path: 'search' do
        get '(:search(/:page))', action: :search, on: :collection,
            as: :search,
            constraints: { page: /\d+/, search: /[^\/]+/ }
      end

      resources :formula, controller: :formulae, only: :show,
                constraints: { id: /[^\/]+/ } do
        get '/version', controller: :api, action: :version, as: :version,
            constraints: { format: :json }, defaults: { format: :json },
            format: nil
      end

      scope format: true, :constraints => { :format => 'atom' } do
        get '/feed' => 'formulae#feed', as: :feed
      end
    end

    resources :formulae, only: :browse, path: 'browse' do
      get ':letter(/:page)', action: :browse, on: :collection,
          as: :letter,
          constraints: { letter: /[A-Za-z]/, page: /\d+/ }
    end

    resources :formulae, only: :browse, path: 'search' do
      get '(:search(/:page))', action: :search, on: :collection,
          as: :search,
          constraints: { page: /\d+/, search: /[^\/]+/ }
    end

    resources :formula, controller: :formulae, only: :show,
              constraints: { id: /[^\/]+/ } do
      get '/version', controller: :api, action: :version, as: :version,
          constraints: { format: :json }, defaults: { format: :json },
          format: nil
    end
  end

  scope format: true do
    scope constraints: { format: :atom } do
      get '/feed', to: 'formulae#feed', as: :feed
    end

    scope constraints: { format: :xml } do
      get '/sitemap', to: 'application#sitemap', as: :sitemap
    end
  end

  root to: 'application#index'
  get '/status', to: 'application#status'

  get '*url', to: 'application#not_found', format: false

  delete '/', to: 'application#forbidden', format: false
  delete '*url', to: 'application#forbidden', format: false
  post '/', to: 'application#forbidden', format: false
  post '*url', to: 'application#forbidden', format: false
  put '/', to: 'application#forbidden', format: false
  put '*url', to: 'application#forbidden', format: false
  match '/', via: :options, to: 'application#forbidden', format: false
  match '*url', via: :options, to: 'application#forbidden', format: false

end

app/views/layouts/_structured_data.html.erb
<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "WebApplication",
    "applicationCategory": "Package browser",
    "dateCreated": "2012-01-06T11:10:35+0100",
    "datePublished": "2012-01-07T01:42:05+0100",
    "image": "<%= url_to_image 'favicon.png' %>",
    "license": "https://opensource.org/licenses/BSD-3-Clause",
    "name": "formulae.brew.sh",
    "operatingSystem": "any",
    "sameAs": "https://twitter.com/braumeister_org",
    "potentialAction": {
      "@type": "SearchAction",
      "target": "<%= search_formulae_url %>/{term}",
      "query-input": "required name=term"
    }
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html itemscope itemtype="http://schema.org/WebPage" lang="en">
<head>
  <title><%= title %></title>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'https://apis.google.com/js/platform.js', defer: true %>
  <%= javascript_include_tag '//platform.twitter.com/widgets.js', defer: true %>

  <%= auto_discovery_link_tag :atom, feed_path(format: :atom) %>
  <%= csrf_meta_tag %>

  <link rel="search" type="application/opensearchdescription+xml" title="formulae.brew.sh" href="/opensearch.xml">
  <%= favicon_link_tag %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= yield :kaminari %>

  <meta http-equiv="content-type" content="text/html;charset=UTF-8">
  <meta itemprop="name" content="formulae.brew.sh">
  <meta itemprop="description" content="An online package browser for Homebrew, the MacOS package manager.">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= render 'layouts/google_analytics' if Rails.env == 'production' %>
  <%= render 'layouts/structured_data' %>
</head>
<body<% unless @repository.nil? || @repository.core? %> data-repository="<%= @repository.name %>"<% end %>>
    <div id="header">
        <%= link_to 'Formulae', root_path %>
    </div>
    <div id="content" class="border-bottom">
        <% if flash[:error] %>
            <div id="flash-error"><%= flash[:error].html_safe %></div>
        <% end %>
        <% if flash[:notice] %>
            <div id="flash-notice"><%= flash[:notice].html_safe %></div>
        <% end %>
        <%= yield %>
    </div>
    <div id="footer" class="border-top">
      <p>
        formulae.brew.sh was created by <a href="https://plus.google.com/109586181974940228820?rel=author">
        Sebastian Staudt</a>.
        View source code on <a href="https://github.com/Homebrew/formulae.brew.sh"><i class="fab fa-lg fa-github"></i> GitHub</a>.
        Follow <a href="https://twitter.com/braumeister_org">@braumeister_org</a>
        on Twitter.
      </p>
    </div>
</body>
</html>